# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sitio Web de Raúl Martínez para HMIS :)
email: rmg429@inlumine.ual.es
description: >- # this means to ignore newlines until "baseurl:"
  Este sitio está dedicado a la asignatura Herramientas y Métodos de Ingeniería del Software, donde se 
  exploran las técnicas y herramientas fundamentales que permiten el desarrollo de software eficiente, 
  de alta calidad y escalable. A lo largo del curso, se abordan temas clave como el ciclo de vida del software, 
  los métodos ágiles, las herramientas de desarrollo y testing, y las mejores prácticas para la gestión 
  de proyectos de software. Este espacio sirve como repositorio de conocimientos, recursos y proyectos 
  prácticos que reflejan los conceptos aprendidos en clase
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: raulmart1nez
github_username:  ualrmg429

# Build settings
theme: minima
plugins:
- jekyll-feed

#theme: hacker
plugins:
  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
